run:
  timeout: 5m
  tests: false        
  concurrency: 2
  skip-dirs:
    - vendor
  skip-files:
    - "*.pb.go"

linters:
  enable:
    - govet           
    - errcheck        
    - staticcheck     
    - gosimple        
    - unused          
    - typecheck       
    - ineffassign     
    - gofmt           
    - misspell        
    - gocritic        
    - whitespace      
    - shadow

linters-settings:
  gofmt:
    simplify: true

issues:
  max-same-issues: 5
  exclude-use-default: true
  exclude:
    - "error return value not checked"